
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.2 EDK_O.61xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: XilKernel Configuration parameters
*
*******************************************************************/

#ifndef _CONFIG_INIT_H
#define _CONFIG_INIT_H



/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.2 EDK_O.61xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: LibXilKernel Initialization structures
*
*******************************************************************/

#include <sys/init.h>
#include <os_config.h>


extern void main_thread();

struct _elf_pthread_init kb_pthread_table[1] = {
	{main_thread,1}
};
#endif
