
# ------------------------------------------------------------------
#
# CAUTION: This file is automatically generated by libgen.
# Version: Xilinx EDK 13.2 EDK_O.61xd
# DO NOT EDIT.
#
# Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

# 
# Description: Configuration parameters for Standalone Makefile
#
# ------------------------------------------------------------------

LIBSOURCES = *.s *.c *.S
LIBS = standalone_libs
