
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.2 EDK_P.28xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_LEDS_GPIO_DEVICE_ID,
		XPAR_LEDS_GPIO_BASEADDR,
		XPAR_LEDS_GPIO_INTERRUPT_PRESENT,
		XPAR_LEDS_GPIO_IS_DUAL
	},
	{
		XPAR_SWITCHES_GPIO_DEVICE_ID,
		XPAR_SWITCHES_GPIO_BASEADDR,
		XPAR_SWITCHES_GPIO_INTERRUPT_PRESENT,
		XPAR_SWITCHES_GPIO_IS_DUAL
	}
};


