
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.2 EDK_O.61xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: MFS Parameters
*
*******************************************************************/

#ifndef _MFS_CONFIG_H
#define _MFS_CONFIG_H
#include <stdio.h>
#include <xilmfs.h>
#define MFS_NUMBYTES  266000
#define MFS_BASE_ADDRESS 0xC5000000
#define MFS_INIT_TYPE  MFSINIT_IMAGE
#endif
