
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.2 EDK_O.61xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemaclite.h"

/*
* The configuration table for devices
*/

XEmacLite_Config XEmacLite_ConfigTable[] =
{
	{
		XPAR_ETHERNET_LITE_DEVICE_ID,
		XPAR_ETHERNET_LITE_BASEADDR,
		XPAR_ETHERNET_LITE_TX_PING_PONG,
		XPAR_ETHERNET_LITE_RX_PING_PONG,
		XPAR_ETHERNET_LITE_INCLUDE_MDIO,
		XPAR_ETHERNET_LITE_INCLUDE_INTERNAL_LOOPBACK
	}
};


